trigger:
  - main
  # - feature/*

pr:
  branches:
    include:
      - '*'

pool: MyPool

variables:
  SonarCloud: 'a6354dba64795f8e71e899f9b94e8c4310a14502'
  SonarOrg: 'timbaronholdings'

steps:
  - checkout: self
    fetchDepth: 0

  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis configuration'
    inputs:
      SonarCloud: 'SonarQube Cloud'
      organization: 'timbaronholdings'
      scannerMode: 'Other'
      extraProperties: |
        sonar.pullrequest.key=$(System.PullRequest.PullRequestId)
        sonar.pullrequest.branch=$(System.PullRequest.SourceBranch)
        sonar.pullrequest.base=$(System.PullRequest.TargetBranch)
        sonar.projectKey=TimbaronHoldings_sonar-validation-pipeline
        sonar.coverage.jacoco.xmlReportPaths=CCReport43F6D5EF/jacoco.xml
        sonar.projectName=sonar-validation-pipeline
        sonar.projectVersion=1.0
        sonar.verbose=true
        sonar.token=a6354dba64795f8e71e899f9b94e8c4310a14502
        sonar.sources=src/main/java
        sonar.tests=src/test/java
        sonar.java.binaries=target
        sonar.qualitygate.wait=true
        sonar.exclusions="**Configuration**"

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      options: 'clean install'
      javaHomeOption: 'Path'
      jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'verify'
      testRunTitle: 'Junit Tests'
      #codeCoverageToolOption: 'JaCoCo'
      mavenVersionOption: 'Default'
      sonarQubeRunAnalysis: false
      #isJacocoCoverageReportXML: false
      sqMavenPluginVersionChoice: 'latest'
      checkStyleRunAnalysis: true

  - task: SonarQubeAnalyze@5
    condition: succeeded()

  - task: SonarQubePublish@5
    condition: succeeded()
    inputs:
      pollingTimeoutSec: '300'