trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sonarQubeServer: 'SonarQube Cloud'
  sonarQubeToken: '$(SONARQUBE_TOKEN)'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: 'clean install'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'verify'

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: '$(sonarQubeServer)'
      scannerMode: 'other'
      configMode: 'file'
      configFile: 'sonar-project.properties'


  - task: SonarQubeAnalyze@5

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'